//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TkbHocPhan
    {
        public int id { get; set; }
        public int Tkb_id { get; set; }
        public string MaHP { get; set; }
        public string TenHocPhan { get; set; }
        public byte TinChi { get; set; }
        public string NhomTo { get; set; }
        public byte Thu { get; set; }
        public string Phong { get; set; }
        public byte TietBatDau { get; set; }
        public byte SoTiet { get; set; }
        public byte SoSV { get; set; }
        public byte TuanBatDau { get; set; }
        public byte TuanKetThuc { get; set; }
        public string Nganh { get; set; }
        public string MaKhoa { get; set; }
    
        public virtual TkbDanhSach TkbDanhSach { get; set; }
    }
}
